### ISSUE TITLE
Terminology

### ISSUE THREAD

**Issue by fivdi** [IainIsCreative/awesome-nodebots#1]
Maybe it would be good to rename sections [Compatibility Libraries](https://github.com/IainIsCreative/awesome-nodebots#compatibility-libraries) and [Plugins](https://github.com/IainIsCreative/awesome-nodebots#plugins).

For example, [Raspi-IO](https://github.com/nebrius/raspi-io) and [BeagleBone-IO](https://github.com/julianduque/beaglebone-io) are IO Plugins, but they are in a section titled `Compatibility Libraries`. On the other hand, there is a section titled `Plugins`. I may be mistaken but would imagine that this will confuse some people.

**Comment by IainIsCreative** [comment]
@fivdi thanks for the tip! I'll look more into it today and see which is the appropriate sub-section for those links. Though perhaps `Compatibility Plugins` would be the appropriate title for that sub-section?

**Comment by IainIsCreative** [comment]
Changed 'Compatibility Libraries' and 'Plugins' to 'IO Compatibility Plugins' and 'Robot Programming Plugins', respectively.

Hope this solves the issue — closing for now.

**Comment by fivdi** [comment]
@IainIsCreative it's better now.
